// Shared rendering for a copilot-backend answer — used by Chat.tsx's message
// list AND Home.tsx's inline quick-reply (Phase 3), so both surfaces render
// Markdown, citations, assumptions/unknowns/warnings/actions, the demo-mode
// badge, and the honest-unavailable state identically, from one place.
import Icon from "./Icon";
import Citations from "./Citations";
import Markdown from "./Markdown";
import type { Citation, CopilotChatResult } from "../types";

function ListSection({ icon, label, items }: { icon: Parameters<typeof Icon>[0]["name"]; label: string; items: string[] }) {
  if (!items.length) return null;
  return (
    <div className="copilot-meta-section">
      <div className="copilot-meta-label"><Icon name={icon} size={12} /> {label}</div>
      <ul className="copilot-meta-list">
        {items.map((it, i) => <li key={i}>{it}</li>)}
      </ul>
    </div>
  );
}

export interface AssistantAnswerData {
  text: string;
  streaming?: boolean;
  citations?: Citation[];
  copilotAssumptions?: string[];
  unknowns?: string[];
  copilotWarnings?: string[];
  recommendedNextActions?: string[];
  copilotUnavailable?: boolean;
  runtimeMode?: "deterministic_demo" | "live_model";
}

// Adapter (Phase 2C/3 principle: one clear adapter, not scattered field
// renaming) from the wire-shaped CopilotChatResult to what this component
// (and Chat.tsx's Message-based rendering) expects.
export function fromCopilotResult(result: CopilotChatResult): AssistantAnswerData {
  const text = result.unavailable
    ? "Grounded analysis is temporarily unavailable right now (the copilot backend could not be reached). "
      + "No repository-grounded answer was generated for this message — please try again shortly."
    : result.answerMarkdown;
  return {
    text,
    citations: result.citations,
    copilotAssumptions: result.assumptions,
    unknowns: result.unknowns,
    copilotWarnings: result.warnings,
    recommendedNextActions: result.recommendedNextActions,
    copilotUnavailable: result.unavailable,
    runtimeMode: result.runtimeMode,
  };
}

export default function AssistantAnswer({ data }: { data: AssistantAnswerData }) {
  const hasMeta = !!(data.citations?.length || data.copilotAssumptions?.length || data.unknowns?.length
    || data.copilotWarnings?.length || data.recommendedNextActions?.length);
  return (
    <>
      {data.runtimeMode === "deterministic_demo" && (
        <div
          className="demo-mode-badge"
          title="Grounded repository data comes from the selected environment. Response wording is generated by the deterministic demo provider."
        >
          <Icon name="alert" size={12} /> Demo mode — deterministic grounded output, not live model synthesis
        </div>
      )}
      {data.text && (
        <div className={`msg-assistant-body${data.copilotUnavailable ? " unavailable" : ""}`}>
          {data.copilotUnavailable && (
            <div className="banner-note" style={{ marginBottom: 8 }}>
              <Icon name="alert" /><span>Grounded analysis is temporarily unavailable.</span>
            </div>
          )}
          {data.copilotUnavailable ? (
            <p>{data.text}</p>
          ) : (
            <Markdown text={data.text} />
          )}
          {data.streaming && <span className="stream-caret" />}
        </div>
      )}
      {!data.streaming && hasMeta && (
        <div className="copilot-meta">
          {data.citations && data.citations.length > 0 && <Citations citations={data.citations} />}
          <ListSection icon="alert" label="Assumptions" items={data.copilotAssumptions ?? []} />
          <ListSection icon="search" label="Unknowns" items={data.unknowns ?? []} />
          <ListSection icon="alert" label="Warnings" items={data.copilotWarnings ?? []} />
          <ListSection icon="check-circle" label="Recommended next actions" items={data.recommendedNextActions ?? []} />
        </div>
      )}
    </>
  );
}
