// Minimal, hand-built OverviewPayload fixture for component/unit tests.
// Shapes mirror executive-ui/api/serialize.py output (types.ts), scaled down.
import type { Opportunity, OverviewPayload } from "../types";

function opp(id: string, name: string): Opportunity {
  return {
    id,
    name,
    raw_score: 42,
    raw_max: 85,
    composite: 3.4,
    classification: "promising",
    classification_label: "Promising",
    confidence: "medium",
    assumption_count: 6,
    factors: [],
    critical_flags: [],
    segment: "Test segment",
    jtbd: "Test JTBD",
    hypothesis: "Test hypothesis",
    strongest_evidence: [],
    contradictory_evidence: "—",
    rejection_conditions: "—",
    validation_plan: "—",
    score_history: [],
    latest_change: "—",
    latest_alert: "—",
    next_action: "—",
    profile_path: "(fixture)",
    is_archived: false,
    impact_history: [],
    brief_envelope: null,
  };
}

export const overviewFixture: OverviewPayload = {
  meta: {
    generated_note: "fixture",
    decision_banner: "No product or build decision has been made.",
    impact_available: true,
    counts: {},
  },
  opportunities: [opp("OPP-001", "Test Opportunity One"), opp("OPP-002", "Test Opportunity Two")],
  archived: [],
  evidence: [
    {
      ev_id: "EV-2026-W28-001",
      resolved: true,
      source_type: "interview",
      evidence_class: "primary",
      strength: 4,
      confidence: "high",
      status: "active",
      segment: "SEG-test",
      title: "Merchants report slow settlement",
      role: "primary",
      weak: false,
      // Phase 4 — complete provenance, fresh
      source_title: "Trustpilot — Telr",
      source_url: "https://trustpilot.com/review/telr.example",
      publisher: "Trustpilot",
      publication_date: "2026-06-30",
      date_of_evidence: "2026-06-30",
      retrieved_at: "2026-07-10",
      created_at: "2026-07-10",
      last_verified_at: "2026-07-11",
      excerpt: "Funds held for more than 2 months with no explanation.",
      access_label: "search-snippet",
      contradictory_evidence: "None found this run",
      freshness_status: "fresh",
      freshness_reference_date: "2026-07-11",
      freshness_age_days: 4,
      freshness_reason: "Last verified 4 days ago.",
      linked_opportunity_ids: ["OPP-001", "OPP-002"],
      linked_assumption_ids: ["OPP-001::willingness_to_pay"],
    },
    {
      // Phase 4 — internal record: no external URL, stale
      ev_id: "EV-2026-W28-002",
      resolved: true,
      source_type: "desk-research",
      evidence_class: "primary",
      strength: 3,
      confidence: "medium",
      status: "active",
      segment: "SEG-test",
      title: "Internal desk research on settlement times",
      role: "contextual",
      weak: false,
      source_title: null,
      source_url: null,
      publisher: null,
      publication_date: null,
      date_of_evidence: null,
      retrieved_at: null,
      created_at: "2025-11-01",
      last_verified_at: "2025-12-13",
      excerpt: null,
      access_label: null,
      contradictory_evidence: null,
      freshness_status: "stale",
      freshness_reference_date: "2025-12-13",
      freshness_age_days: 214,
      freshness_reason: "Last verified 214 days ago. Older than the 180-day staleness threshold.",
      linked_opportunity_ids: [],
      linked_assumption_ids: [],
    },
    {
      // Phase 4 — legacy/partial record: unsafe URL from backend (must never
      // render as a link), unknown freshness, most fields absent
      ev_id: "EV-2026-W28-003",
      resolved: true,
      source_type: "—",
      evidence_class: "primary",
      strength: 2,
      confidence: "low",
      status: "needs-more-evidence",
      segment: "—",
      title: "Partially recorded lead",
      role: "contextual",
      weak: true,
      source_url: "javascript:alert(1)",
      freshness_status: "unknown",
      freshness_reason: "No verification, retrieval, publication, or creation date is available for this record.",
    },
  ],
  assumptions: [
    {
      opportunity_id: "OPP-001",
      factor_key: "willingness_to_pay",
      text: "Merchants will pay a monthly fee for faster settlement.",
      status: "untested",
      evidence_ids: [],
      sensitivity: "high",
      validation_method: "interview",
      owner: "Product",
      decision_importance: "high",
      source: "fixture",
    },
  ],
  feed: [
    {
      id: "EVT-001",
      kind: "lead",
      tier: "informative",
      title: "New evidence record EV-2026-W28-001",
      detected_at: "2026-07-12",
      detail: "EV-2026-W28-001",
      before_after: null,
    },
    {
      id: "EVT-002",
      kind: "prediction-resolved",
      tier: "informative",
      title: "Prediction resolved",
      detected_at: "2026-07-13",
      detail: "Resolved as expected",
      before_after: { before: "p=60%", after: "true" },
    },
    {
      id: "EVT-003",
      kind: "score-change",
      tier: "important",
      title: "Opportunity rescored",
      detected_at: "2026-07-14",
      detail: "OPP-001",
      before_after: null,
    },
  ],
  briefs: [{ opportunity_id: "OPP-001", exists: true, path: "(fixture)", body: "# Recommendation\n\nDo the thing." }],
  impact_proposals: [],
};
